'use client';

import React, { useEffect, useState, useRef } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import {
  ArrowLeft,
  ArrowRight,
  Mic,
  Square,
  RefreshCw,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  Loader2,
  ChevronDown,
  ChevronUp,
  RotateCcw,
  Keyboard,
  Send,
  Award,
} from 'lucide-react';
import { useVoiceRecorder } from '@/hooks/useVoiceRecorder';
import {
  getRole,
  transcribeAudio,
  generateInterviewQuestion,
  analyzeInterviewAnswer,
  getFinalInterviewFeedback,
  RolewiseApiError,
} from '@/services/api';
import { Role, CommunicationAnalysisResponse, FinalFeedbackOutput } from '@/types/database';

type InterviewFlowState =
  | 'READY'
  | 'RECORDING'
  | 'RECORDED'
  | 'PROCESSING'
  | 'TRANSCRIBED'
  | 'ANALYZING'
  | 'REVIEWED'
  | 'TYPING'
  | 'COMPLETED';

interface CompletedRound {
  questionNumber: number;
  question: string;
  competency: string;
  answerType: 'voice' | 'text';
  transcript: string;
  durationSeconds?: number;
  analysis: CommunicationAnalysisResponse;
}

export default function InterviewPage() {
  const params = useParams();

  const roleId = params?.id as string;

  // Role details
  const [role, setRole] = useState<Role | null>(null);

  // Session & question state
  const [questionNumber, setQuestionNumber] = useState<number>(1);
  const [currentQuestion, setCurrentQuestion] = useState<string>('');
  const [currentCompetency, setCurrentCompetency] = useState<string>('');
  const [isLoadingSession, setIsLoadingSession] = useState<boolean>(true);

  // Flow State Machine
  const [flowState, setFlowState] = useState<InterviewFlowState>('READY');
  const [transcriptText, setTranscriptText] = useState<string>('');
  const [typedAnswer, setTypedAnswer] = useState<string>('');
  const [isTranscriptExpanded, setIsTranscriptExpanded] = useState<boolean>(true);

  // Communication Analysis Result for current question
  const [currentAnalysis, setCurrentAnalysis] = useState<CommunicationAnalysisResponse | null>(null);

  // History across questions
  const [completedRounds, setCompletedRounds] = useState<CompletedRound[]>([]);
  const [aiFinalFeedback, setAiFinalFeedback] = useState<FinalFeedbackOutput | null>(null);

  // Pending next question generated by AI
  const [pendingNext, setPendingNext] = useState<{
    question: string;
    competency: string;
  } | null>(null);

  // Error handling
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [lastFailedAction, setLastFailedAction] = useState<(() => void) | null>(null);

  // Voice recorder hook
  const {
    isPermissionDenied,
    permissionError,
    formattedDuration,
    startRecording,
    stopRecording,
    resetRecording,
    clearPermissionError,
  } = useVoiceRecorder();

  // Keep a reference of the recorded audio blob for re-trying transcription if needed
  const recordedBlobRef = useRef<{ blob: Blob; durationSeconds: number; audioUrl: string } | null>(null);
  const [recordedAudioUrl, setRecordedAudioUrl] = useState<string | null>(null);

  // Total questions in an interview session
  const totalQuestions = 5;

  // Initialize Role & Initial Question
  useEffect(() => {
    async function init() {
      if (!roleId) return;

      try {
        const fetchedRole = await getRole(roleId);
        if (!fetchedRole) {
          setRole(null);
          setIsLoadingSession(false);
          return;
        }

        setRole(fetchedRole);

        // Fetch dynamic first question from interview-ai Edge Function
        try {
          const generated = await generateInterviewQuestion({
            roleId,
            questionNumber: 1,
            previousQuestions: [],
          });
          if (generated.question) {
            setCurrentQuestion(generated.question);
          }
          if (generated.competency) {
            setCurrentCompetency(generated.competency);
          }
        } catch (genErr) {
          console.error('[InterviewPage] Question generation notice:', genErr);
          const msg = genErr instanceof Error ? genErr.message : 'AI question generation unavailable';
          setErrorMessage(msg);
        }
      } catch (err: unknown) {
        console.error('Error initializing interview:', err);
      } finally {
        setIsLoadingSession(false);
      }
    }

    init();
  }, [roleId]);

  // Handle Start Recording
  const handleStartRecording = async () => {
    setErrorMessage(null);
    clearPermissionError();

    const success = await startRecording();
    if (success) {
      setFlowState('RECORDING');
    }
  };

  // Handle Stop Recording (Requirement 15: Stop -> Real Blob created -> Show duration & Play recording -> Review -> Continue)
  const handleStopRecording = async () => {
    setErrorMessage(null);

    const recorded = await stopRecording();
    if (!recorded || !recorded.blob) {
      setErrorMessage("Couldn't capture audio. Please try again.");
      setFlowState('READY');
      return;
    }

    recordedBlobRef.current = recorded;
    setRecordedAudioUrl(recorded.audioUrl);
    setFlowState('RECORDED');
  };

  // Proceed from RECORDED state to AI Transcription & Analysis
  const handleProceedToAIAnalysis = async () => {
    if (!recordedBlobRef.current) return;
    setFlowState('PROCESSING');
    setErrorMessage(null);

    try {
      const response = await transcribeAudio(
        recordedBlobRef.current.blob,
        recordedBlobRef.current.durationSeconds
      );
      setTranscriptText(response.transcript);
      setIsTranscriptExpanded(true);
      await handleAnalyzeAnswer(response.transcript, 'voice');
    } catch (err: unknown) {
      console.error('Transcription / analysis error:', err);
      setErrorMessage('Your recording was captured, but AI feedback is temporarily unavailable.');
      setLastFailedAction(() => handleProceedToAIAnalysis);
      // Keep recording available in RECORDED state (Requirement 16)
      setFlowState('RECORDED');
    }
  };

  // Re-record action
  const handleReRecord = () => {
    resetRecording();
    recordedBlobRef.current = null;
    setTranscriptText('');
    setErrorMessage(null);
    setFlowState('READY');
  };

  // Submit Answer for AI Communication Analysis (both voice transcript & typed answer)
  const handleAnalyzeAnswer = async (answerText: string, type: 'voice' | 'text') => {
    if (!answerText.trim()) return;

    setFlowState('ANALYZING');
    setErrorMessage(null);

    const previousAnswers = completedRounds.map((r) => r.transcript);

    try {
      const analysisResult = await analyzeInterviewAnswer({
        roleId,
        question: currentQuestion,
        transcript: answerText.trim(),
        previousAnswers,
      });
      setCurrentAnalysis(analysisResult);

      // Record this round
      const newRound: CompletedRound = {
        questionNumber,
        question: currentQuestion,
        competency: currentCompetency,
        answerType: type,
        transcript: answerText.trim(),
        durationSeconds: type === 'voice' ? recordedBlobRef.current?.durationSeconds : undefined,
        analysis: analysisResult,
      };

      setCompletedRounds((prev) => [...prev, newRound]);

      // Stage next question or follow-up
      if (analysisResult.next_question) {
        setPendingNext({
          question: analysisResult.next_question,
          competency: analysisResult.next_competency || currentCompetency,
        });
      } else {
        setPendingNext(null);
      }

      setFlowState('REVIEWED');
    } catch (err: unknown) {
      console.error('Communication analysis error:', err);
      const msg = err instanceof Error ? err.message : 'AI feedback is temporarily unavailable.';
      setErrorMessage(msg);
      setLastFailedAction(() => () => handleAnalyzeAnswer(answerText, type));
      // Stay on current answer state so the user doesn't lose their transcript/typed text (Requirement 16)
      setFlowState(type === 'voice' ? 'RECORDED' : 'TYPING');
    }
  };

  // Move to Next Question or Complete
  const handleContinueInterview = async () => {
    if (questionNumber >= totalQuestions || !pendingNext) {
      setFlowState('COMPLETED');
      // Fetch dynamic final feedback from interview-ai Edge Function
      try {
        const finalRes = await getFinalInterviewFeedback({
          roleId,
          answers: completedRounds.map((r) => ({
            question: r.question,
            transcript: r.transcript,
            analysis: r.analysis,
          })),
        });
        setAiFinalFeedback(finalRes);
      } catch (err) {
        console.warn('[InterviewPage] Final feedback synthesis notice:', err);
      }
      return;
    }

    setQuestionNumber((prev) => prev + 1);
    setCurrentQuestion(pendingNext.question);
    setCurrentCompetency(pendingNext.competency);
    setPendingNext(null);
    setCurrentAnalysis(null);
    setTranscriptText('');
    setTypedAnswer('');
    resetRecording();
    recordedBlobRef.current = null;
    setRecordedAudioUrl(null);
    setErrorMessage(null);
    setFlowState('READY');
  };

  // Practice again (restart session)
  const handlePracticeAgain = () => {
    setQuestionNumber(1);
    setCurrentQuestion('');
    setCurrentCompetency('');
    setPendingNext(null);
    setCurrentAnalysis(null);
    setAiFinalFeedback(null);
    setCompletedRounds([]);
    setTranscriptText('');
    setTypedAnswer('');
    resetRecording();
    recordedBlobRef.current = null;
    setRecordedAudioUrl(null);
    setErrorMessage(null);
    setFlowState('READY');

    generateInterviewQuestion({ roleId, questionNumber: 1, previousQuestions: [] })
      .then((res) => {
        if (res.question) setCurrentQuestion(res.question);
        if (res.competency) setCurrentCompetency(res.competency);
      })
      .catch((err) => {
        const msg = err instanceof Error ? err.message : 'AI question generation unavailable';
        setErrorMessage(msg);
      });
  };

  if (isLoadingSession) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] gap-3 text-[#667085]">
        <Loader2 className="w-7 h-7 animate-spin text-[#6D5DFB]" />
        <p className="text-sm font-medium">Setting up interview session…</p>
      </div>
    );
  }

  if (!role) {
    return (
      <div className="space-y-6 max-w-xl mx-auto py-12 text-center animate-in fade-in">
        <div className="rolewise-card p-8 space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-[#FFF0ED] text-[#E87967] flex items-center justify-center mx-auto">
            <AlertCircle className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h2 className="text-xl font-semibold text-[#1F2937]">Role not found</h2>
            <p className="text-sm text-[#667085]">
              Return to your roles and select a valid role.
            </p>
          </div>
          <div className="pt-2">
            <Link
              href="/"
              className="touch-target inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-sm font-medium transition-colors shadow-sm"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Return to Dashboard</span>
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // 11. FINAL FEEDBACK VIEW
  if (flowState === 'COMPLETED') {
    // Compile aggregate strengths & improvements from actual answers
    const allStrengths = completedRounds.flatMap((r) => r.analysis.strengths).slice(0, 4);
    const allImprovements = completedRounds.flatMap((r) => r.analysis.improvements).slice(0, 4);

    // Qualitative pattern summaries
    const clarityCount = completedRounds.filter((r) => r.analysis.communication_feedback.clarity === 'Strong').length;
    const structureCount = completedRounds.filter((r) => r.analysis.communication_feedback.structure === 'Strong').length;
    const specificityCount = completedRounds.filter((r) => r.analysis.communication_feedback.specificity === 'Strong').length;
    const concisenessCount = completedRounds.filter((r) => r.analysis.communication_feedback.conciseness === 'Strong').length;

    const claritySummary =
      clarityCount >= completedRounds.length / 2
        ? 'Direct and articulate throughout responses. Thoughts were expressed with conviction and minimal hesitation.'
        : 'Ideas were conveyed, but periodically drifted into tangential details before returning to the core question.';

    const structureSummary =
      structureCount >= completedRounds.length / 2
        ? 'Consistent logical framing across answers. Clear progression from problem context to action to resolution.'
        : 'Tendency to jump directly into actions without establishing baseline constraints and stakeholder situation.';

    const specificitySummary =
      specificityCount >= completedRounds.length / 2
        ? 'Concrete details were highlighted effectively, referencing explicit tools, constraints, and methodologies.'
        : 'Answers relied more on general principles than granular examples. Ground responses in tangible project artifacts.';

    const concisenessSummary =
      concisenessCount >= completedRounds.length / 2
        ? 'Paced and concise delivery. Avoided rambling and kept responses focused on key contributions.'
        : 'Answers were occasionally verbose. Practice condensing background context and focusing on direct outcomes.';

    const finalStrengths =
      aiFinalFeedback?.strengths && aiFinalFeedback.strengths.length > 0
        ? aiFinalFeedback.strengths
        : allStrengths;

    const finalImprovements =
      aiFinalFeedback?.areas_to_improve && aiFinalFeedback.areas_to_improve.length > 0
        ? aiFinalFeedback.areas_to_improve
        : allImprovements;

    const finalClarity = aiFinalFeedback?.communication?.clarity || claritySummary;
    const finalStructure = aiFinalFeedback?.communication?.structure || structureSummary;
    const finalSpecificity = aiFinalFeedback?.communication?.specificity || specificitySummary;
    const finalConciseness = aiFinalFeedback?.communication?.conciseness || concisenessSummary;
    const finalExercises =
      aiFinalFeedback?.practice_exercises && aiFinalFeedback.practice_exercises.length > 0
        ? aiFinalFeedback.practice_exercises
        : null;

    return (
      <div className="max-w-3xl mx-auto space-y-6 pb-12 animate-in fade-in duration-300">
        {/* Top exit */}
        <div className="flex items-center justify-between">
          <Link
            href={`/roles/${roleId}/preparation`}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-[#667085] hover:text-[#1F2937] transition-colors touch-target"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to preparation</span>
          </Link>
          <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-[#EAF6F0] text-[#4E9B76] border border-[#C6EBD7]">
            Session Completed
          </span>
        </div>

        {/* Header */}
        <section className="space-y-1">
          <div className="flex items-center gap-2 text-xs font-medium text-[#667085]">
            <span className="font-semibold text-[#1F2937]">{role.title}</span>
            {role.company && (
              <>
                <span>·</span>
                <span>{role.company}</span>
              </>
            )}
          </div>
          <h1 className="text-2xl sm:text-3xl font-semibold text-[#1F2937] tracking-tight">
            Your interview feedback
          </h1>
          <p className="text-xs sm:text-sm text-[#667085]">
            Communication practice review based on your spoken and written responses.
          </p>
        </section>

        {/* Feedback Cards */}
        <div className="space-y-4">
          {/* What went well */}
          <div className="rolewise-card p-6 space-y-3">
            <h2 className="text-sm font-semibold text-[#1F2937] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[#4E9B76]" />
              <span>What went well</span>
            </h2>
            <ul className="space-y-2 text-xs sm:text-sm text-[#1F2937]">
              {finalStrengths.length > 0 ? (
                finalStrengths.map((strength, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-[#4E9B76] font-bold">✓</span>
                    <span>{strength}</span>
                  </li>
                ))
              ) : (
                <li className="text-[#667085]">Demonstrated role familiarity and communicated your experience.</li>
              )}
            </ul>
          </div>

          {/* What to improve */}
          <div className="rolewise-card p-6 space-y-3">
            <h2 className="text-sm font-semibold text-[#1F2937] flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-[#C58A2B]" />
              <span>What to improve</span>
            </h2>
            <ul className="space-y-2 text-xs sm:text-sm text-[#1F2937]">
              {finalImprovements.length > 0 ? (
                finalImprovements.map((improvement, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-[#C58A2B] font-bold">•</span>
                    <span>{improvement}</span>
                  </li>
                ))
              ) : (
                <li className="text-[#667085]">Continue practicing structuring actions and articulating measurable outcomes.</li>
              )}
            </ul>
          </div>

          {/* Communication patterns */}
          <div className="rolewise-card p-6 space-y-4">
            <h2 className="text-sm font-semibold text-[#1F2937]">Communication patterns</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
              <div className="p-3.5 rounded-xl bg-[#F7F7FB] border border-[#E7E8EF] space-y-1">
                <span className="text-xs font-semibold text-[#1F2937]">Clarity</span>
                <p className="text-xs text-[#667085] leading-relaxed">{finalClarity}</p>
              </div>

              <div className="p-3.5 rounded-xl bg-[#F7F7FB] border border-[#E7E8EF] space-y-1">
                <span className="text-xs font-semibold text-[#1F2937]">Structure</span>
                <p className="text-xs text-[#667085] leading-relaxed">{finalStructure}</p>
              </div>

              <div className="p-3.5 rounded-xl bg-[#F7F7FB] border border-[#E7E8EF] space-y-1">
                <span className="text-xs font-semibold text-[#1F2937]">Specificity</span>
                <p className="text-xs text-[#667085] leading-relaxed">{finalSpecificity}</p>
              </div>

              <div className="p-3.5 rounded-xl bg-[#F7F7FB] border border-[#E7E8EF] space-y-1">
                <span className="text-xs font-semibold text-[#1F2937]">Conciseness</span>
                <p className="text-xs text-[#667085] leading-relaxed">{finalConciseness}</p>
              </div>
            </div>
          </div>

          {/* Practice next */}
          <div className="rolewise-card p-6 space-y-3 bg-[#EEECFF]/30 border-[#D8D4FD]">
            <h2 className="text-sm font-semibold text-[#6D5DFB] flex items-center gap-2">
              <Award className="w-4 h-4" />
              <span>Practice next</span>
            </h2>
            <div className="space-y-2.5 text-xs sm:text-sm text-[#1F2937]">
              {finalExercises ? (
                finalExercises.map((exercise, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-white border border-[#D8D4FD]/60">
                    <p className="font-semibold text-xs text-[#6D5DFB]">{idx + 1}. Recommended Drill</p>
                    <p className="text-xs text-[#667085] mt-0.5 leading-relaxed">{exercise}</p>
                  </div>
                ))
              ) : (
                <>
                  <div className="p-3 rounded-xl bg-white border border-[#D8D4FD]/60">
                    <p className="font-semibold text-xs text-[#6D5DFB]">1. Behavioral Structure Exercise</p>
                    <p className="text-xs text-[#667085] mt-0.5 leading-relaxed">
                      Practice answering behavioral questions using: <strong>Situation → Action → Result</strong>. Ensure your Action receives 60% of your answer time.
                    </p>
                  </div>
                  <div className="p-3 rounded-xl bg-white border border-[#D8D4FD]/60">
                    <p className="font-semibold text-xs text-[#6D5DFB]">2. Measurable Outcome Drill</p>
                    <p className="text-xs text-[#667085] mt-0.5 leading-relaxed">
                      For every project scenario, prepare one metric of success (e.g., user completion rate, latency reduction, cross-team adoption).
                    </p>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="pt-2 flex flex-col sm:flex-row items-center gap-3">
            <button
              type="button"
              onClick={handlePracticeAgain}
              className="w-full sm:w-1/2 touch-target inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-sm font-medium transition-colors shadow-sm cursor-pointer"
            >
              <RotateCcw className="w-4 h-4" />
              <span>Practice again</span>
            </button>

            <Link
              href={`/roles/${roleId}/preparation`}
              className="w-full sm:w-1/2 touch-target inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-white hover:bg-[#F7F7FB] text-[#1F2937] border border-[#E7E8EF] text-sm font-medium transition-colors shadow-sm"
            >
              <span>Back to preparation</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // ACTIVE INTERVIEW FLOW
  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-12 animate-in fade-in duration-300">
      {/* Top Header Bar */}
      <div className="flex items-center justify-between">
        <Link
          href={`/roles/${roleId}/preparation`}
          className="inline-flex items-center gap-1.5 text-xs font-medium text-[#667085] hover:text-[#1F2937] transition-colors touch-target"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Exit to preparation</span>
        </Link>

        {/* Progress Counter */}
        <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-[#EEECFF] text-[#6D5DFB] border border-[#D8D4FD]">
          Question {questionNumber} of {totalQuestions}
        </span>
      </div>

      {/* Role Header */}
      <section className="space-y-1">
        <div className="flex items-center gap-2 text-xs font-medium text-[#667085]">
          <span className="font-semibold text-[#1F2937]">{role.title}</span>
          {role.company && (
            <>
              <span>·</span>
              <span>{role.company}</span>
            </>
          )}
        </div>
        <h1 className="text-2xl sm:text-3xl font-semibold text-[#1F2937] tracking-tight">
          AI Interview
        </h1>
      </section>

      {/* Permission Denied Warning */}
      {isPermissionDenied && (
        <div className="p-4 rounded-xl bg-[#FFF0ED] border border-[#FBD2CB] text-[#E87967] text-xs sm:text-sm space-y-2 animate-in fade-in">
          <div className="flex items-start gap-2.5">
            <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold">Microphone access is needed for voice practice.</p>
              <p className="text-xs mt-0.5 text-[#1F2937]">
                {permissionError || 'Please allow microphone access in your browser to practice speaking your answers.'}
              </p>
            </div>
          </div>
          <div className="pt-1 flex items-center gap-3">
            <button
              type="button"
              onClick={handleStartRecording}
              className="touch-target px-3 py-1.5 rounded-lg bg-white border border-[#E87967]/40 text-[#E87967] hover:bg-[#FFF0ED] text-xs font-medium transition-colors"
            >
              Try again
            </button>
            <button
              type="button"
              onClick={() => {
                clearPermissionError();
                setFlowState('TYPING');
              }}
              className="touch-target px-3 py-1.5 rounded-lg bg-[#1F2937] text-white hover:bg-black text-xs font-medium transition-colors"
            >
              Answer by typing
            </button>
          </div>
        </div>
      )}

      {/* General Error Notice / Quota Exceeded */}
      {errorMessage && (
        <div className="p-4 rounded-xl bg-[#FFF0ED] border border-[#FBD2CB] text-[#E87967] text-xs sm:text-sm space-y-2 animate-in fade-in">
          <div className="flex items-start gap-2.5">
            <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold">Notice</p>
              <p className="text-xs mt-0.5 text-[#1F2937]">{errorMessage}</p>
            </div>
          </div>
          <div className="pt-1 flex flex-wrap items-center gap-3">
            {lastFailedAction && (
              <button
                type="button"
                onClick={() => {
                  setErrorMessage(null);
                  lastFailedAction();
                }}
                className="touch-target inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-[#E87967]/40 text-[#E87967] hover:bg-[#FFF0ED] text-xs font-medium transition-colors cursor-pointer"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Retry</span>
              </button>
            )}
            <button
              type="button"
              onClick={handlePracticeAgain}
              className="touch-target inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-[#E7E8EF] text-[#1F2937] hover:bg-[#F7F7FB] text-xs font-medium transition-colors cursor-pointer"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Practice again</span>
            </button>
            {flowState !== 'TYPING' && (
              <button
                type="button"
                onClick={() => {
                  setErrorMessage(null);
                  if (transcriptText && !typedAnswer) {
                    setTypedAnswer(transcriptText);
                  }
                  setFlowState('TYPING');
                }}
                className="touch-target px-3 py-1.5 rounded-lg bg-white border border-[#E7E8EF] text-[#1F2937] hover:bg-[#F7F7FB] text-xs font-medium transition-colors cursor-pointer"
              >
                Type answer instead
              </button>
            )}
          </div>
        </div>
      )}

      {/* Main Question Card */}
      <section className="rolewise-card p-6 space-y-3">
        <div className="flex items-center justify-between">
          <span className="inline-flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full bg-[#EEECFF] text-[#6D5DFB] border border-[#D8D4FD]">
            <Sparkles className="w-3.5 h-3.5" />
            {currentCompetency || 'Role Competency'}
          </span>
          <span className="text-xs text-[#667085]">
            Question {questionNumber} of {totalQuestions}
          </span>
        </div>

        {currentQuestion ? (
          <h2 className="text-base sm:text-lg font-semibold text-[#1F2937] leading-relaxed">
            &ldquo;{currentQuestion}&rdquo;
          </h2>
        ) : (
          <div className="py-2 text-[#667085] text-sm">
            {errorMessage ? (
              <span className="text-[#E87967]">Question generation failed. See error notice above.</span>
            ) : (
              <span className="inline-flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-[#6D5DFB]" />
                Generating question based on role requirements...
              </span>
            )}
          </div>
        )}

        <p className="text-xs text-[#667085] pt-1">
          Answer naturally. ROLEWISE will evaluate both your response and how you communicate it.
        </p>
      </section>

      {/* RECORDING & INPUT INTERACTION STATES */}

      {/* STATE 1: READY */}
      {flowState === 'READY' && (
        <div className="rolewise-card p-6 space-y-6 text-center animate-in fade-in">
          <div className="max-w-md mx-auto space-y-2">
            <h3 className="text-sm font-semibold text-[#1F2937]">Answer by voice</h3>
            <p className="text-xs text-[#667085]">
              Speak clearly into your microphone as if in a live conversation.
            </p>
          </div>

          <div className="flex flex-col items-center justify-center gap-3">
            <button
              type="button"
              onClick={handleStartRecording}
              className="touch-target inline-flex items-center justify-center gap-2.5 px-6 py-3 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-sm font-medium transition-colors shadow-sm cursor-pointer"
            >
              <Mic className="w-5 h-5" />
              <span>Start recording</span>
            </button>

            <button
              type="button"
              onClick={() => {
                clearPermissionError();
                setFlowState('TYPING');
              }}
              className="text-xs text-[#667085] hover:text-[#1F2937] transition-colors underline pt-2 cursor-pointer"
            >
              Type instead
            </button>
          </div>
        </div>
      )}

      {/* STATE 2: RECORDING */}
      {flowState === 'RECORDING' && (
        <div className="rolewise-card p-6 space-y-6 text-center animate-in fade-in">
          <div className="flex flex-col items-center justify-center gap-3">
            {/* Animated recording indicator */}
            <div className="flex items-center gap-2.5 px-3.5 py-1.5 rounded-full bg-[#FFF0ED] border border-[#FBD2CB] text-[#E87967]">
              <span className="w-2.5 h-2.5 rounded-full bg-[#E87967] animate-pulse" />
              <span className="text-xs font-semibold uppercase tracking-wider">Recording...</span>
            </div>

            {/* Elapsed Time Display */}
            <div className="text-2xl sm:text-3xl font-mono font-semibold text-[#1F2937]">
              {formattedDuration}
            </div>

            <p className="text-xs text-[#667085]">
              Speaking now. Click stop when you have completed your answer.
            </p>
          </div>

          <div className="flex justify-center">
            <button
              type="button"
              onClick={handleStopRecording}
              className="touch-target inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#E87967] hover:bg-[#D96B5A] text-white text-sm font-medium transition-colors shadow-sm cursor-pointer"
            >
              <Square className="w-4 h-4 fill-current" />
              <span>Stop recording</span>
            </button>
          </div>
        </div>
      )}

      {/* STATE 2.5: RECORDED (Review audio before AI analysis - Requirement 15 & 16) */}
      {flowState === 'RECORDED' && (
        <div className="rolewise-card p-6 space-y-5 text-center animate-in fade-in">
          <div className="space-y-1">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#EAF6F0] text-[#4E9B76] text-xs font-semibold">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Recording captured ({formattedDuration})</span>
            </div>
            <h3 className="text-sm font-semibold text-[#1F2937] pt-2">Listen to your response</h3>
            <p className="text-xs text-[#667085]">
              Review your recording before submitting for AI communication analysis.
            </p>
          </div>

          {recordedAudioUrl && (
            <div className="max-w-md mx-auto pt-1">
              <audio controls src={recordedAudioUrl} className="w-full h-10 rounded-xl" />
            </div>
          )}

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <button
              type="button"
              onClick={handleReRecord}
              className="touch-target inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-white border border-[#E7E8EF] hover:bg-[#F7F7FB] text-[#1F2937] text-sm font-medium transition-colors cursor-pointer"
            >
              <RotateCcw className="w-4 h-4 text-[#667085]" />
              <span>Re-record</span>
            </button>

            <button
              type="button"
              onClick={handleProceedToAIAnalysis}
              className="touch-target inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-sm font-medium transition-colors shadow-sm cursor-pointer"
            >
              <span>Continue with this answer</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STATE 3: PROCESSING TRANSCRIPTION */}
      {flowState === 'PROCESSING' && (
        <div className="rolewise-card p-8 space-y-3 text-center animate-in fade-in">
          <Loader2 className="w-6 h-6 animate-spin text-[#6D5DFB] mx-auto" />
          <h3 className="text-sm font-semibold text-[#1F2937]">Understanding your answer...</h3>
          <p className="text-xs text-[#667085]">
            Transcribing speech and extracting key communication points.
          </p>
        </div>
      )}

      {/* STATE 4: TRANSCRIBED ("You said") */}
      {flowState === 'TRANSCRIBED' && (
        <div className="space-y-4 animate-in fade-in">
          <div className="rolewise-card p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#667085]">
                You said
              </span>
              <button
                type="button"
                onClick={() => setIsTranscriptExpanded(!isTranscriptExpanded)}
                className="text-xs text-[#667085] hover:text-[#1F2937] inline-flex items-center gap-1 cursor-pointer"
              >
                <span>{isTranscriptExpanded ? 'Collapse' : 'Expand'}</span>
                {isTranscriptExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              </button>
            </div>

            {isTranscriptExpanded && (
              <p className="text-xs sm:text-sm text-[#1F2937] leading-relaxed whitespace-pre-wrap bg-[#F7F7FB] p-3.5 rounded-xl border border-[#E7E8EF]">
                {transcriptText}
              </p>
            )}
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-between gap-3">
            <button
              type="button"
              onClick={handleReRecord}
              className="w-full sm:w-auto touch-target inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-white hover:bg-[#F7F7FB] text-[#667085] hover:text-[#1F2937] border border-[#E7E8EF] text-xs sm:text-sm font-medium transition-colors cursor-pointer"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Re-record</span>
            </button>

            <button
              type="button"
              onClick={() => handleAnalyzeAnswer(transcriptText, 'voice')}
              className="w-full sm:w-auto touch-target inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-xs sm:text-sm font-medium transition-colors shadow-sm cursor-pointer"
            >
              <span>Continue</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STATE 5: AI ANALYSIS LOADING */}
      {flowState === 'ANALYZING' && (
        <div className="rolewise-card p-8 space-y-3 text-center animate-in fade-in">
          <Loader2 className="w-6 h-6 animate-spin text-[#6D5DFB] mx-auto" />
          <h3 className="text-sm font-semibold text-[#1F2937]">Analyzing communication quality…</h3>
          <p className="text-xs text-[#667085]">
            Evaluating relevance, clarity, structure, and outcome alignment.
          </p>
        </div>
      )}

      {/* STATE 6: COMPACT COMMUNICATION PRACTICE FEEDBACK */}
      {flowState === 'REVIEWED' && currentAnalysis && (
        <div className="space-y-4 animate-in fade-in">
          <section className="rolewise-card p-6 space-y-4 border-[#4E9B76]/30 bg-[#EAF6F0]/20">
            <div className="flex items-center gap-2 text-sm font-semibold text-[#4E9B76]">
              <CheckCircle2 className="w-4 h-4" />
              <span>Answer reviewed</span>
            </div>

            {/* What worked */}
            <div className="space-y-1.5">
              <span className="text-xs font-semibold text-[#1F2937]">What worked</span>
              <ul className="space-y-1 text-xs text-[#1F2937]">
                {currentAnalysis.strengths.map((str, idx) => (
                  <li key={idx} className="flex items-start gap-1.5">
                    <span className="text-[#4E9B76] font-bold">✓</span>
                    <span>{str}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Improve */}
            <div className="space-y-1.5 pt-1 border-t border-[#E7E8EF]">
              <span className="text-xs font-semibold text-[#1F2937]">Improve</span>
              <ul className="space-y-1 text-xs text-[#1F2937]">
                {currentAnalysis.improvements.map((imp, idx) => (
                  <li key={idx} className="flex items-start gap-1.5">
                    <span className="text-[#C58A2B] font-bold">•</span>
                    <span>{imp}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Communication dimensions */}
            <div className="space-y-2 pt-1 border-t border-[#E7E8EF]">
              <span className="text-xs font-semibold text-[#1F2937]">Communication</span>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                <div className="p-2.5 rounded-xl bg-white border border-[#E7E8EF] space-y-0.5">
                  <span className="text-[#667085] text-[11px]">Clarity</span>
                  <p className="font-semibold text-[#1F2937]">{currentAnalysis.communication_feedback.clarity}</p>
                </div>
                <div className="p-2.5 rounded-xl bg-white border border-[#E7E8EF] space-y-0.5">
                  <span className="text-[#667085] text-[11px]">Structure</span>
                  <p className="font-semibold text-[#1F2937]">{currentAnalysis.communication_feedback.structure}</p>
                </div>
                <div className="p-2.5 rounded-xl bg-white border border-[#E7E8EF] space-y-0.5">
                  <span className="text-[#667085] text-[11px]">Specificity</span>
                  <p className="font-semibold text-[#1F2937]">{currentAnalysis.communication_feedback.specificity}</p>
                </div>
                <div className="p-2.5 rounded-xl bg-white border border-[#E7E8EF] space-y-0.5">
                  <span className="text-[#667085] text-[11px]">Conciseness</span>
                  <p className="font-semibold text-[#1F2937]">{currentAnalysis.communication_feedback.conciseness}</p>
                </div>
              </div>
            </div>

            {/* Continue interview button */}
            <div className="pt-2 flex justify-end">
              <button
                type="button"
                onClick={handleContinueInterview}
                className="touch-target w-full sm:w-auto inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-[#6D5DFB] hover:bg-[#5A48F5] text-white text-xs sm:text-sm font-medium transition-colors shadow-sm cursor-pointer"
              >
                <span>{questionNumber >= totalQuestions ? 'View feedback' : 'Continue interview →'}</span>
              </button>
            </div>
          </section>
        </div>
      )}

      {/* STATE 7: TYPING FALLBACK */}
      {flowState === 'TYPING' && (
        <div className="space-y-4 animate-in fade-in">
          <div className="rolewise-card p-6 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-[#1F2937] flex items-center gap-2">
                <Keyboard className="w-4 h-4 text-[#6D5DFB]" />
                <span>Type your answer</span>
              </span>
              <span className="text-xs text-[#667085]">
                {typedAnswer.length} characters
              </span>
            </div>

            <textarea
              rows={5}
              value={typedAnswer}
              onChange={(e) => setTypedAnswer(e.target.value)}
              placeholder="Structure your answer using concrete actions and measurable outcomes..."
              className="w-full p-4 rounded-xl border border-[#E7E8EF] text-xs sm:text-sm text-[#1F2937] placeholder:text-[#667085]/60 focus:outline-none focus:border-[#6D5DFB] bg-white transition-colors resize-y leading-relaxed font-normal"
            />

            <p className="text-xs text-[#667085]">
              Prefer to speak? You can switch back to voice practice anytime.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-between gap-3">
            <button
              type="button"
              onClick={() => {
                setTypedAnswer('');
                setFlowState('READY');
              }}
              className="touch-target inline-flex items-center gap-1.5 text-xs text-[#667085] hover:text-[#1F2937] cursor-pointer"
            >
              <Mic className="w-3.5 h-3.5" />
              <span>Switch to voice</span>
            </button>

            <button
              type="button"
              onClick={() => handleAnalyzeAnswer(typedAnswer, 'text')}
              disabled={!typedAnswer.trim()}
              className={`w-full sm:w-auto touch-target inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl text-xs sm:text-sm font-medium transition-colors shadow-sm ${
                typedAnswer.trim()
                  ? 'bg-[#6D5DFB] hover:bg-[#5A48F5] text-white cursor-pointer'
                  : 'bg-[#E7E8EF] text-[#667085] cursor-not-allowed opacity-80'
              }`}
            >
              <span>Continue with answer</span>
              <Send className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
